### PR TITLE
Metapool LP breakdowns

### PR DESCRIPTION
**Pull request by BrknRobot**
This adds support for metapool LP breakdowns. Any nested LPs will be replaced by it's held tokens in the display. I think it could be nice to continue showing the nested LP in our breakdown, but that was more UI work than I felt like doing.

2022-07-13T23:01:16,290757838-05:00

### CODE REVIEW

**Comment by roman-monk** [comment]
looks great. what if we show underlying tokens (without am*)?
can do this by enforcing "underlyingToken" property in all curvePools and then add it to API breakdown and match in app.

**Comment by roman-monk** [comment]
new field "underlyingToken" to the lps/breakdown API. app will have to match underlyingToken || token for breakdown.
those tokens are already in the address-book.

**Comment by MirthFutures** [comment]
This is really cool @BrknRobot. 

@roman-monk wdyt?

**Comment by roman-monk** [comment]
yeah its very nice, i still think displaying underlying tokens as we do in filters and vault names would be more user friendly than "Aave Matic Market Dai"

**Pull request closed without merging**
