### PR TITLE
Add MAI 4pool

### PR DESCRIPTION
**Pull request by cartman-dev**
* beefyfinance/beefy-api#973

```
Vault: 0xffbf83be790e184a57584d3faF40505eA1ECab3f
Strategy: 0x9346FC872C563CA71147BDEfddEFe7cEC8e2d56c
Want: 0xEceab9F0FcF15Fddbffbd7baE2cEB78CD57b879a
Pool Id: 33
```

### CODE REVIEW

**Comment by MirthFutures** [comment]
@cartman-dev 
image

**Comment by cartman-dev** [comment]
This is how the old one shows up too. It's being treated as an LP, but the front end doesn't know how to break down the pool component. Is there a front end change that needs to happen? Can we choose not show this breakdown for metapools?

**Comment by MirthFutures** [comment]
The way I have handled until we get a meta breakdown is to have the 3 pool as it's own asset in addressbook.

**Comment by cartman-dev** [comment]
@MirthFutures Updated addressbook in beefyfinance/beefy-api#973, changed front end to use the `stella4pool` token, and added image.

**Comment by MirthFutures** [comment]
> @MirthFutures Updated addressbook in [beefyfinance/beefy-api#973](https://github.com/beefyfinance/beefy-api/pull/973), changed front end to use the `stella4pool` token, and added image.

Can you bump addressbook to 0.39.30

**Comment by cartman-dev** [comment]
> Can you bump addressbook to 0.39.30

I did, then I reverted it because main has moved on to more recent versions and this was left in conflict.

**Pull request merged**
