### PR TITLE
Add Curve/Convex TriCRV vault.

### PR DESCRIPTION
**Pull request by defymcdefiface**
API: https://github.com/beefyfinance/beefy-api/pull/1457

mooConvexTriCRV
Vault 0x1d46d2B6A3d83bB33Feb7b8e7EdFb73e9937befD
Strategy 0x367a0970bA47Ea29c97Bbe354c964b829686b92f

Tested with `VAULT=0x1d46d2B6A3d83bB33Feb7b8e7EdFb73e9937befD forge test --fork-url http://localhost:8545 --match-contract StrategyCurveConvexTest`, and limited manual testing after deployment(very expensive deposits / withdrawals). 
`yarn validate` passes.

### CODE REVIEW

**Comment by defymcdefiface** [comment]
@roman-monk, gentle ping.

**Comment by roman-monk** [comment]
@defymcdefiface you need to verify strategy contract.
ideally it should be deployed as minimal proxy to existing implementation, but if you used correct source code its ok.
please use flattening for verification (single file).

**Comment by defymcdefiface** [comment]
Thanks, missed this in the instructions, the strategy contract is now verified. Will use a minimal proxy deployment next time, seems like a much better route from cost and testing standpoint.

**Comment by roman-monk** [comment]
we cant accept this deployment.
i would expect the flat contract from the beefy-contracts repo to match your deployment.
but you modified the strategy code and even Base strategy code which is quite unusual.

please redeploy using minimal proxy as you did for the vault, you can use this address as impl `0xeB3616a2Ea38e21C59Cd8Eded6d2A8bC937a0A87`

**Comment by defymcdefiface** [comment]
Yep I did something dumb, verified with my debugging remnants in the repo. Re-deployed as proxies and updated.

**Comment by defymcdefiface** [comment]
Hey @roman-monk, PTAL when you get a chance.

**Comment by defymcdefiface** [comment]
Hey @roman-monk, is there anything else I need to do here?

**Pull request merged**
