### PR TITLE
Vault/biswap etc bnb

### PR DESCRIPTION
**Pull request by bowlingotter**
Vault: 0xF1237FbbD307d515DE8839dB93b1a91287C600F6
Strategy: 0x299036033B8080bed95192C7CB9F72D19ba8832D
Want: 0x1Cba970a6E06d4BcC0c4717BE677d1A8AA0211DA
PoolId: 110

### CODE REVIEW

**Comment by MirthFutures** [comment]
Withdraw wasnt tested

**Comment by bowlingotter** [comment]
> Withdraw wasnt tested

Apologies -- tested since, merge conflict resolved

**Comment by roman-monk** [comment]
no image

**Comment by bowlingotter** [comment]
etc.png added

**Comment by bowlingotter** [comment]
> no image

ETC.png added

**Pull request merged**
