### PR TITLE
Add Balancer sAVAX-AVAX and VeloV2 WETH-wrsETH vaults

### PR DESCRIPTION
**Pull request by schnarkus**
API: https://github.com/beefyfinance/beefy-api/pull/1436

VeloV2 WETH-wrsETH
Vault https://optimistic.etherscan.io/address/0xdbe946e16c4e0de9a44065b868265ac05c437fb6
Strat https://optimistic.etherscan.io/address/0x292145ee0a52a4b1cf7ec6ae26f7e1ebdaea0d73

Aero WETH-wrsETH
Vault 0xC5cD1A6d4918820201B8E4eeB6d2AdFD1CDF783d
Strat 0x74d1A204aca72260Bf5c68e1DEC30AB972a81665

Moo Balancer Avax sAVAX-WAVAX
Vault 0x883b1899e6F8a896Ee22654A6deBA41Ef4BA47Cf
Strat 0x09cD0B51DF0A2E8C6238dD269f2f3c789d13b809
Contract is verified: https://snowtrace.io/address/0x8eA4805A0652FF9Bc06311cB98c7178873B4b13C/contract/43114/code

### CODE REVIEW

**Comment by kexleyBeefy** [comment]
@schnarkus Is output address correct? The BAL reward is then not being swapped to native?

**Comment by schnarkus** [comment]
> @schnarkus Is output address correct? The BAL reward is then not being swapped to native?

yes, pulled the wrong ca from the address book

**Comment by schnarkus** [comment]
API: https://github.com/beefyfinance/beefy-api/pull/1436

VeloV2 WETH-wrsETH
Vault https://optimistic.etherscan.io/address/0xdbe946e16c4e0de9a44065b868265ac05c437fb6
Strat https://optimistic.etherscan.io/address/0x292145ee0a52a4b1cf7ec6ae26f7e1ebdaea0d73

**Comment by kexleyBeefy** [comment]
Adding vaults to lrt-subgraph before merging

**Pull request merged**
