### PR TITLE
[Feat] Quickswap Gamma BOB-USDC Stable Stategy

### PR DESCRIPTION
**Pull request by Hephyrius**
Vault: [0x370E8c60A9C99A43Cef89b48496676Ba251f6D23](https://polygonscan.com/address/0x370E8c60A9C99A43Cef89b48496676Ba251f6D23)
Strategy: [0x5Eed4e3b4bF7de3746b30C860aB1674758EABb8b](https://polygonscan.com/address/0x5eed4e3b4bf7de3746b30c860ab1674758eabb8b)

### CODE REVIEW

**Comment by roman-monk** [comment]
not sure if BOB is safe, looks like proxy without timelock

**Comment by Hephyrius** [comment]
> not sure if BOB is safe, looks like proxy without timelock

The deployment of bob on polygon looks almost identical to that on optimism. Key difference is no timelock. The end admin of both token contracts proxies is the same, a gnosis safe controlled by the zkmoney protocol.

**Comment by MirthFutures** [comment]
> > not sure if BOB is safe, looks like proxy without timelock
> 
> The deployment of bob on polygon looks almost identical to that on optimism. Key difference is no timelock. The end admin of both token contracts proxies is the same, a gnosis safe controlled by the zkmoney protocol.

I'll ask the Bob Team to timelock before you close this.

**Comment by MirthFutures** [comment]
> > not sure if BOB is safe, looks like proxy without timelock
> 
> The deployment of bob on polygon looks almost identical to that on optimism. Key difference is no timelock. The end admin of both token contracts proxies is the same, a gnosis safe controlled by the zkmoney protocol.

Good news, They agreed and timelocked the proxy. Can you fix conflicts so we can merge?

**Comment by Hephyrius** [comment]
> > > not sure if BOB is safe, looks like proxy without timelock
> > 
> > 
> > The deployment of bob on polygon looks almost identical to that on optimism. Key difference is no timelock. The end admin of both token contracts proxies is the same, a gnosis safe controlled by the zkmoney protocol.
> 
> Good news, They agreed and timelocked the proxy. Can you fix conflicts so we can merge?

Hey sorry for the late response - this slipped my radar - conflict is resolved!

**Pull request merged**
