### PR TITLE
EOL QuickSwap Gamma vaults which will not harvest

### PR DESCRIPTION
**Pull request by EPETE-EPETE**
quick-gamma-usdc-dai-narrow
quick-gamma-usdc-weth-wide
quick-gamma-wbtc-weth-wide
quick-gamma-weth-usdt
quick-gamma-wmatic-quick
quick-gamma-wmatic-usdc-wide
quick-gamma-wmatic-weth-wide

### CODE REVIEW

**Comment by EPETE-EPETE** [comment]
Rewards:
pancake-ichi-usdt-wbnb
pancake-ichi-usdt-btcb
pancake-ichi-cake-usdt
sushi-base-gamma-weth-usdbc-narrow
sushi-gamma-weth-usdc-narrow
uniswap-gamma-btc.b-weth
sushi-gamma-magic-weth-narrow

aura-r-dai
moonwell-base-weth

**Comment by EPETE-EPETE** [comment]
Revive:
netswap-weth-m.usdc
stargate-metis-usdt

**Comment by erenjaegar77** [comment]
> Revive: netswap-weth-m.usdc stargate-metis-usdt

image

**Comment by EPETE-EPETE** [comment]
also EOL
uniswap-gamma-gdai-dai
uniswap-gamma-gns-usdc-narrow
uniswap-gamma-gns-usdc-wide
uniswap-gamma-gns-weth-wide

**Pull request merged**
